# Generated by Django 3.1.3 on 2020-12-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60)),
                ('document', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('registrationDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
